### ISSUE TITLE
BUG: Badge not generating from committed testReport.csv 

### ISSUE THREAD

**Issue by flybonzai** [cicirello/jacoco-badge-generator#150]
**Describe the bug**
Due to gradle hanging when trying to run tests or a jacoco test report in github actions itself, we have a pre-commit hook to generate the report file and put it in a stable location at `<<project-root-name>>/code-coverage/test/jacocoTestReport.csv`.  I have then configured the badge report step to look for this file as follows:

```
    steps:
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: 'code-coverage/test/jacocoTestReport.csv'
```

I have tried with both the relative path and a glob.  When running, I receive the error:

```
WARNING: Report file **jacocoTestReport.csv does not exist or glob **jacocoTestReport.csv is empty.
WARNING: No JaCoCo csv reports found.
```

**To Reproduce**
1. Place a report .csv file in a stable directory in the repository and point the above job step at it.

**Expected behavior**
The badge can be generated from a pre-existing, committed file.

**Relevant System Info (please complete the following information):**
 - Github Actions with `ubuntu-latest`
