### ISSUE TITLE
BUG: file not found in Multi-module

### ISSUE THREAD

**Issue by cprudhom** [cicirello/jacoco-badge-generator#18]
I have a two-module project and I use TestNG as testing framework, which allows (like JUnit I believe) to declare groups.
I declared 8 groups, (a) some are tagged in both modules, (b) some in only one of them.
I configured this GitHub action in order to list jacoco-csv files but in (b) case only one exists.

When I run the action, it throws `FileNotFoundError: [Errno 2] No such file or directory: 'solver/target/site/jacoco/jacoco.csv'` which is expected. But I wonder whether it is possible to add something like:
```python
if os.path. exists(filename):
```
just before [JacocoBadgeGenerator.py#L90](https://github.com/cicirello/jacoco-badge-generator/blob/458dabdcfbbbc9f2fd68b9f251d42212073d163f/JacocoBadgeGenerator.py#L90).

**Comment by cicirello** [comment]
I can do that. I considered that to begin with, but decided not to check, with the rationale that a missing jacoco.csv may be due to a typo in a workflow file, and that letting the workflow fail would draw attention to such a bug, while simply skipping it would report a coverage percentage that may be inaccurate. 

I guess I can skip missing reports, but log them.

**Comment by cprudhom** [comment]
I found a way around it, uploading and downloading artifacts.
It makes the workflow a bit complex and I'm afraid it will raise another problem.
It also requires to call `merge` action from `maven-jacoco-plugin` in `coverage` profile of `pom.xml`.
  
Here is a bunch of code (sorry, it is a bit long):
```yaml
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    # Tests matrix
    strategy:
      #fail-fast: false
      matrix:
        group: [ "gr1" , "gr2", "gr3" ]

    # The different steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Regression tests
      - name: Test ${{ matrix.group }}
        run: mvn -B --file pom.xml package -Pcoverage -DtestFailureIgnore=true -Dgroups=${{ matrix.group }}

      # upload jacoco-csv files
      - name: Prepare upload
        run: mkdir -p jacoco/
      - run: cp modul1/target/site/jacoco/jacoco.csv jacoco/mod1.csv
      - run: cp module2/target/site/jacoco/jacoco.csv jacoco/mod2.csv
        if: ${{ always() }}
      - name: Upload jacoco-csv files
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.group }}
          path: |
            jacoco/mod1.csv
            jacoco/mod2.csv
          if-no-files-found: ignore

  coverage:
    needs: [ test-suite ]
    runs-on: ubuntu-latest
    steps:
      # Download jacoco-csv files
      - uses: actions/download-artifact@v2
        name: Download jacoco-csv files
        with:
          path: jacoco/

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.1.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            jacoco/gr1/mod1.csv
            jacoco/gr1/mod2.csv
            jacoco/gr2/mod1.csv
#          jacoco/gr2/mod2.csv does not exist
#          jacoco/gr3/mod1.csv does not exist 
            jacoco/gr3/mod2.csv 

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
```

That worked but problem is that I'm sure additions [JacocoBadgeGenerator.py#L94](https://github.com/cicirello/jacoco-badge-generator/blob/458dabdcfbbbc9f2fd68b9f251d42212073d163f/JacocoBadgeGenerator.py#L94) reflect the union expected.
