### ISSUE TITLE
Add Code Coverage badge example repo

### ISSUE THREAD

**Issue by nachg** [cicirello/jacoco-badge-generator#19]
It will be great to have any link to the working example

**Comment by cicirello** [comment]
I'm using it myself in multiple repositories.  Would adding a link to the following work as an example: [example workflow](https://github.com/cicirello/Chips-n-Salsa/blob/master/.github/workflows/build.yml) and the [maven pom.xml](https://github.com/cicirello/Chips-n-Salsa/blob/master/pom.xml)?  In that project, I have jacoco configured in a profile in the pom.xml. Or are you looking for a more minimal example?

**Comment by nachg** [comment]
I think it will be enough. I have injected your badge into my project: https://github.com/nachg/xpathqs also. It is working great!
My suggestion is to add an example badge snippet to the readme.md with the default config:
```[![Coverage](.github/badges/jacoco.svg)](jacoco.svg)```

And add an example of committing changes in the most simple way (buid.yml):
```    
  - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'upload badge'
          add: '*.svg'
```
