### ISSUE TITLE
Add ability to Fail the pipeline if the code coverage was decreased

### ISSUE THREAD

**Issue by nachg** [cicirello/jacoco-badge-generator#21]
I want to implement the code coverage check as a required verification step for the PR's to the master branch. 
I think that it is possible to implement it as an additional feature for the **jacoco-badge-generator**.
example:

```
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.1.0
        with:
          fail-on-decrese: true
```

Also, it will be great to have such option as:
```
    fail-when-coverage-lessThan: 60
```

Which will fail the pipeline when coverage is less than provided argument.
